apiVersion: v1
kind: ConfigMap
metadata:
  name: fixmypaper-config
  namespace: fixmypaper
data:
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "fixmypaper-prod-bucket"
  GROBID_URL: "http://grobid:8070"
  REDIS_URL: "redis://fixmypaper-redis:6379/0"
  # NEXT_PUBLIC_API_URL is now managed in Vercel
