apiVersion: v1
kind: ServiceAccount
metadata:
  name: fixmypaper-sa
  namespace: fixmypaper
  annotations:
    # Use IAM Roles for Service Accounts (IRSA)
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/fixmypaper-eks-role
