apiVersion: v1
kind: Service
metadata:
  name: fixmypaper-api
  namespace: fixmypaper
spec:
  selector:
    app: fixmypaper-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fixmypaper-ingress
  namespace: fixmypaper
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:REGION:ACCOUNT:certificate/ID
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  rules:
  - host: api.fixmypaper.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: fixmypaper-api
            port:
              number: 80
